
obj-y += eth_stats_hooks.o
obj-y += eth_switch_hooks.o
obj-y += ntc_shaper_hooks.o
obj-y += ppp_stats_hooks.o
obj-y += dev_igmpsn_hooks.o
obj-y += dev_pthrough_hooks.o
obj-y += nat_offload_hooks.o
obj-y += nf_conntrack_hooks.o
obj-y += ndm_timer.o
obj-y += ndm_percpu.o
obj-y += xhci_uasp.o
