# SPDX-License-Identifier: GPL-2.0
spinand-objs := core.o alliancememory.o ato.o esmt.o etron.o foresee.o
spinand-objs += fudanmicro.o gigadevice.o heyang.o macronix.o micron.o
spinand-objs += paragon.o toshiba.o winbond.o xtx.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
