#ifndef _UAPI_LINUX_MTK_WIFI_H
#define _UAPI_LINUX_MTK_WIFI_H

#define MTK_GENL_FAMILY_NAME		"mtk_wifiN"
#define MTK_GENL_FAMILY_VERSION		1

#define MTK_GENL_FAMILY_NAME_BAND_POS	\
	(sizeof(MTK_GENL_FAMILY_NAME) - 1 /*N*/ - 1 /*\0*/)

enum {
	MTK_GENL_CMD_UNSPEC = 0,
	MTK_GENL_CMD_GET_SITE_SURVEY,
	MTK_GENL_CMD_MAX,
};

enum {
	MTK_GENL_ATTR_UNSPEC = 0,
	MTK_GENL_ATTR_TIMESTAMP,
	MTK_GENL_ATTR_CHANNEL,
	MTK_GENL_ATTR_SECONDARY_CHANNEL,
	MTK_GENL_ATTR_BANDWIDTH,
	MTK_GENL_ATTR_SSID,
	MTK_GENL_ATTR_BSSID,
	MTK_GENL_ATTR_AUTH_MODE,
	MTK_GENL_ATTR_ENCRYPTION_MODE,
	MTK_GENL_ATTR_SIGNAL_QUALITY,
	MTK_GENL_ATTR_RSSI,
	MTK_GENL_ATTR_WIRELESS_MODE,
	MTK_GENL_ATTR_NETWORK_TYPE,
	MTK_GENL_ATTR_WPS_AP,
	MTK_GENL_ATTR_WPS_DEVICE_PASS_ID,
	MTK_GENL_ATTR_WPS_SETUP_LOCKED,
	MTK_GENL_ATTR_WPS_MANUFACTURER,
	MTK_GENL_ATTR_WPS_MODEL_NAME,
	MTK_GENL_ATTR_WPS_MODEL_NUMBER,
	MTK_GENL_ATTR_WPS_DEVICE_NAME,
	MTK_GENL_ATTR_KEENTIC_MAP_BACKHAUL,
	MTK_GENL_ATTR_CHANNEL_LOAD,
	MTK_GENL_ATTR_STA_NUMBER,
	MTK_GENL_ATTR_COUNTRY_CODE,
	MTK_GENL_ATTR_PAD,
	MTK_GENL_ATTR_MAX,
};

enum {
	MTK_WIFI_WMODE_INVALID	= 0,
	MTK_WIFI_WMODE_A	= 1 << 0,
	MTK_WIFI_WMODE_B	= 1 << 1,
	MTK_WIFI_WMODE_G	= 1 << 2,
	MTK_WIFI_WMODE_GN	= 1 << 3,
	MTK_WIFI_WMODE_AN	= 1 << 4,
	MTK_WIFI_WMODE_AC	= 1 << 5,
	MTK_WIFI_WMODE_AX_24G	= 1 << 6,
	MTK_WIFI_WMODE_AX_5G	= 1 << 7,
	MTK_WIFI_WMODE_AX_6G	= 1 << 8,
};

enum {
	MTK_WIFI_BANDWIDTH_20	= 0,
	MTK_WIFI_BANDWIDTH_40	= 1,
	MTK_WIFI_BANDWIDTH_2040 = 2,
	MTK_WIFI_BANDWIDTH_80	= 3,
	MTK_WIFI_BANDWIDTH_160	= 4,
	MTK_WIFI_BANDWIDTH_8080	= 5,
};

enum {
	MTK_WIFI_NETWORK_TYPE_ADHOC	= 0,
	MTK_WIFI_NETWORK_TYPE_INFRA	= 1,
	MTK_WIFI_NETWORK_TYPE_ANY	= 2,
	MTK_WIFI_NETWORK_TYPE_MONITOR	= 3,
};

enum {
	MTK_WIFI_WPS_DEVICE_PASS_ID_PIN		= 0,
	MTK_WIFI_WPS_DEVICE_PASS_ID_USER	= 1,
	MTK_WIFI_WPS_DEVICE_PASS_ID_MACHINE	= 2,
	MTK_WIFI_WPS_DEVICE_PASS_ID_REKEY	= 3,
	MTK_WIFI_WPS_DEVICE_PASS_ID_PBC		= 4,
	MTK_WIFI_WPS_DEVICE_PASS_ID_REG		= 5,
	MTK_WIFI_WPS_DEVICE_PASS_ID_SMPBC	= 6,
};

#endif /* _UAPI_LINUX_MTK_WIFI_H */
