dtb-$(CONFIG_MACH_MT7622) += mt7622-ac2600rfb1.dtb
dtb-$(CONFIG_MACH_MT7981) += mt7981-spim-nand-rfb.dtb
dtb-$(CONFIG_MACH_MT7986) += mt7986a-spim-nand-rfb.dtb
dtb-$(CONFIG_MACH_MT7986) += mt7986b-spim-nand-rfb.dtb

#dtb-$(CONFIG_ARCH_MEDIATEK) += mt6755-evb.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt6795-evb.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-evb.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
